name: C++ CI

on:
  push:
    branches: [ feature/switch_to_xmake ]
  pull_request:
    branches: [ feature/switch_to_xmake ]


env:
  VULKAN_SDK: C:/VulkanSDK/1.2.182.0

jobs:
  build-windows:
  
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
                
    # Build engine Release
    - name: compile-release
      shell: cmd
      run: |
        xmake
        
  build-linux:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
                
    # Build engine Release
    - name: compile-release
      shell: bash
      run: |
        xmake

  build-macos:
  
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
                
    # Build engine Release
    - name: compile-release
      shell: bash
      run: |
        xmake
